#!/bin/sh
# SPDX-FileCopyrightText: 2026 SyuanTsai
# SPDX-License-Identifier: Apache-2.0
set -eu
hook_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$hook_dir"
exec pwsh -NoProfile -NonInteractive -File Invoke-PrePushValidation.ps1 -RemoteName "$1" -RemoteUrl "$2"
